// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MWAdminRunner
{
    internal sealed partial class Vsix
    {
        public const string Id = "MWAdminRunner.0125b84c-5178-498d-bee9-7110abaf5f1a";
        public const string Name = "MWAdminRunner";
        public const string Description = @"This Will Run Middleware Project Locally . It will modify the required Files and run it locally . Made by Himanshu Kumar Sharma and Namya H S.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Himanshu kumar Sharma && Namya HS  ";
        public const string Tags = "";
    }
}
